version: "3"
services:
  cache:
    image: redis:alpine
    networks:
      - backend
  api:
    build:
      context: .
    depends_on:
      - cache
    environment:
      - REDIS_DEV=redis://cache
    ports:
      - "3000:3000"
    volumes:
      - "./:/shuttle-tracking"
    env_file:
      - .env
    networks:
      - backend
networks:
  backend:
