version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6
        environment: 
          ENV: dev
          REDIS: redis://localhost:6379
      - image: redis@sha256:54057dd7e125ca41afe526a877e8bd35ec2cdd33b9217e022ed37bdcf7d09673
    steps:
      - checkout
      - run:
          name: Dockerize v0.6.0
          command: |
            wget https://github.com/jwilder/dockerize/releases/download/v0.6.0/dockerize-linux-amd64-v0.6.0.tar.gz
            sudo rm -rf /usr/local/bin/dockerize
            sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.0.tar.gz
            rm dockerize-linux-amd64-v0.6.0.tar.gz
      - run:
          name: Wait for Redis
          command: |
            dockerize -wait tcp://localhost:6379 -timeout 1m
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
  test:
    docker:
      - image: circleci/python:3.6
      - image: redis@sha256:54057dd7e125ca41afe526a877e8bd35ec2cdd33b9217e022ed37bdcf7d09673
    steps:
      - checkout
      - run:
        name: Test
        command: pytest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test